version: '3.6'
services:
  php:
    build: ./docker/images/php
    links:
      - db:db
    volumes:
      - ./src/:/var/www/html
  db:
    image: mariadb:10.3
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./docker/db:/var/lib/mysql
    env_file:
      - .env
  nginx:
    image: nginx:latest
    links:
      - php:php
    ports:
      - 127.0.0.1:80:80
    volumes:
      - ./src/:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
  node:
    image: node:10-jessie
    working_dir: /home/node/app
    volumes:
      - ./log/node/:/root/.npm/_logs
      - ./src/:/home/node/app
    expose:
      - 8081
    command: sh -c "npm install && npm run dev"